Support for 7" Ampire display
Openvario/meta-openvario pull request #113
Opened 2021-01-15 11:36 UTC by glidero

Support for 7" Ampire display, type AM-1280800P3TZQW-00H-AMPI, resulution: 1280x800, brightness: 1500 cd/m2, LVDS interface, 24-bit color depth

2021-01-15 21:01 UTC, kedder requested changes
Thanks a lot! This looks good to me, just remove that bak file - they are not very useful considering the file history git provides.

2021-01-15 22:22 UTC, glidero commented on recipes-bsp/u-boot/files/openvario-7-AMPI/openvario_defconfig.bak
> +CONFIG_ARM=y
thanks, the .bak file has been deleted

2021-01-15 22:53 UTC, kedder approved these changes
LGTM, recommend merging with  "Squash and Merge" option.

2021-01-16 08:15 UTC, linuxianer99 requested changes
Please change the name to 
openvario-7-AM070
to be consistend with existing machines

2021-01-16 13:12 UTC, linuxianer99 approved these changes

2021-01-16 13:13 UTC, merged